### ISSUE TITLE
Implementing a 'filter' option to choose which 'fields' you wish to validate or to be returned from parsing?

### ISSUE THREAD

**Issue by ThorrStevens** [diegohaz/schm#27]
Hi, I've been playing around with this solution in combination with Mongoose and have been loving it so far.

One thing I'm missing though is the ability to choose which fields you either:
- ... want back after parsing (something similar to how mongoose does it with their fields filter)
- ... wish to validate (for edge cases when validating certain fields isn't necessary)

Is a way to implement this functionality already by any chance?

Thanks in advance and congrats on creating this awesome package!

**Comment by diegohaz** [comment]
You can modify `parse` and `validate` methods by extending the schema. For example:

```js
const schema = require('schm')
const omit = require('lodash/omit')

const ignore = (...params) => prevSchema => prevSchema.merge({
  parse(values) {
    return prevSchema.parse(omit(values, prams))
  },
  validate(values) {
    return prevSchema.validate(omit(values, params))
  }
})

const mySchema = schema(
  {
    foo: String,
    bar: String,
  },
  ignore('foo'),
)
```

Does it work for you?

**Comment by ThorrStevens** [comment]
Aha, I'd already gotten a similar solution working based on lodash/pick 👍

`
import _ from 'lodash';

module.exports = (obj, schema, options = {}) => {

  // Defaults
  if (typeof options.fields === 'undefined') options.fields = '';

  // Parse obj
  let _obj = schema.parse(obj);

  // # No Filter
  if (options.fields === '') return _obj;

  // Return cherrypicked props
  const requestedKeys = options.fields.split(' ');
  _obj = _.pick(_obj, requestedKeys);
  return _obj;

};
`

But I didn't know I could simply extend it like this without needing the schm-methods package as well, so this will definitely help me further, thanks!

**Comment by ThorrStevens** [comment]
I'm still a bit confused as to how extension like in the example you provided actually works.

Does this add ignore as a callable method on the schema? (with variable arguments)

In the end result I'm looking for I'd like to be able to define extensions and call them like so:

```
MySchema.validateWithOptions(obj, { omit: "name.middle" }); // Ignores name.middle in validation
MySchema.parseWithOptions(obj, { fields: "name.first name.last foo bar" }); // Cherrypick fields
``` 

Is this something that's possible with your proposed solution?
also; 
Can methods defined by 'schm-methods' also reference the schema they're called on itself?

Because if that's the case I could then just pass the helper/util I already wrote as method like so:

```
const MySchema = schema(
   { ... }, 
   methods(
      parseWithOptions: (obj, options) => parseWithSchemaUtil(obj, _this_, options),
   )
);
```

Would that be possible? Or is there another way to add a "plugin" to a schema?

**Comment by diegohaz** [comment]
@ThorrStevens 

This is the interface of `schema`:
```js
schema(...schemas)
```

Passing a literal object to `schema` is the same as using `group` (when you pass a literal object, it's passed to `group` under the hood):
```js
// these are the same
schema({ foo: String })
schema(group({ foo: String }))
```

The implementation of `group` is something like this:
```js
const group = params => prevSchema => prevSchema.merge({ params })
```

The result of `prevSchema.merge({ params })` is the schema itself, which is an object with this structure:
```js
{
  params: Object,
  parse: Function,
  validate: Function,
  parsers: Object,
  validators: Object,
  merge: Function,
}
```

That said, if you want to call `MySchema.validateWithOptions` you need to add the method to the object above. And you can do that the same way that `group` added `params`:
```js
const withValidateWithOptions = prevSchema => prevSchema.merge({
  validateWithOptions(values, options) {
    return validateWithOptions(values, this, options)
  }
})

const mySchema = schema({ ... }, withValidateWithOptions)

mySchema.validateWithOptions({ ... }, options)
```

**Comment by diegohaz** [comment]
To clarify, `schm-methods` adds methods to the parsed object:
```js
const mySchema = schema(
  { ... }, 
  methods({
    foo: () => {}
  })
)

const parsed = mySchema.parse({ ... })

parsed.foo()
```

Maybe docs aren't clear enough. If you find a better way to explain it there I'll be glad to accept a PR. :)
