### ISSUE TITLE
JSON validation

### ISSUE THREAD

**Issue by seriousme** [diegohaz/schm#29]
I tried to comment on your [article on Medium](https://medium.freecodecamp.org/how-to-write-powerful-schemas-in-javascript-490da6233d37), but somehow that seems to be impossible. Anyway:

The note on AJV is incorrect. AJV is able to verify documents on the full JSON Schema spec (http://json-schema.org/) Including string patterns, enums, min, max etc.

An example can be found at: https://npm.runkit.com/ajv

It also offers conditional validation as decribed at: https://medium.com/@quentin.chevrin/ajv-a-solution-to-form-validation-f1d12e767f0

Added benefit is that there's loads of tools to help in creaction and validation of schemas.
http://json-schema.org/implementations.html

And if you are using schema validation in an API you might want to look at https://swagger.io/ which also uses JSON schema :-)

Of course you are free to reinvent the wheel :-) Just wanted to clarify that AJV does more than checking defaults and types ;-)

**Comment by diegohaz** [comment]
Hi, @seriousme.

I have no idea what's the problem with Medium comments. Everything seems to be working well there.

About `ajv`, text might be confusing, but I was talking only about parsing features:
> Also, even though `ajv` **has some parsing features**, they're limited to default values and type coercion.

Thank you for your feedback.
