### ISSUE TITLE
[methods] Install problem

### ISSUE THREAD

**Issue by strategicmachines** [diegohaz/schm#30]
Thank you for pulling this project together. We're very excited about testing it

I am encountering an install issue on schm-method. I noted you fixed and closed the same issue on schm -- related to scripts/documentation

Or since this is a mono-repo -- am I suppose to handle npm install differently? Any help would be appreciated

Thx

**Comment by diegohaz** [comment]
It seems that some error occurred when publishing the fix on `schm-methods`. Could you please try to install it again?

**Comment by diegohaz** [comment]
Closing this since problem seems to be fixed.

**Comment by pdhoward** [comment]
I am the guy who opened the issue for Strategic Machines. I retested Work perfect! Thanks much!
